-- liquibase formatted sql

-- changeset dip4rip:1713271640981-1
CREATE TABLE composers
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100),
    CONSTRAINT pk_composers PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-2
CREATE TABLE genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-3
CREATE TABLE media_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_media_types PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-4
CREATE TABLE music
(
    inventory_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    genre_id         INTEGER,
    title            VARCHAR(100),
    performer_id     INTEGER,
    composer_id      INTEGER,
    media_type_id    INTEGER,
    record_label_id  INTEGER,
    recording_date   date,
    CONSTRAINT pk_music PRIMARY KEY (inventory_number)
);

-- changeset dip4rip:1713271640981-5
CREATE TABLE performers
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100),
    CONSTRAINT pk_performers PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-6
CREATE TABLE playlist
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100),
    user_id INTEGER,
    CONSTRAINT pk_playlist PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-7
CREATE TABLE playlist_music
(
    playlist_id      INTEGER NOT NULL,
    inventory_number INTEGER NOT NULL,
    CONSTRAINT pk_playlist_music PRIMARY KEY (playlist_id, inventory_number)
);

-- changeset dip4rip:1713271640981-8
CREATE TABLE record_labels
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100),
    CONSTRAINT pk_record_labels PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-9
CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(100),
    address   VARCHAR(200),
    phone     VARCHAR(20),
    login     VARCHAR(50),
    password  VARCHAR(50),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset dip4rip:1713271640981-10
ALTER TABLE music
    ADD CONSTRAINT FK_MUSIC_ON_COMPOSER FOREIGN KEY (composer_id) REFERENCES composers (id);

-- changeset dip4rip:1713271640981-11
ALTER TABLE music
    ADD CONSTRAINT FK_MUSIC_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genres (id);

-- changeset dip4rip:1713271640981-12
ALTER TABLE music
    ADD CONSTRAINT FK_MUSIC_ON_MEDIA_TYPE FOREIGN KEY (media_type_id) REFERENCES media_types (id);

-- changeset dip4rip:1713271640981-13
ALTER TABLE music
    ADD CONSTRAINT FK_MUSIC_ON_PERFORMER FOREIGN KEY (performer_id) REFERENCES performers (id);

-- changeset dip4rip:1713271640981-14
ALTER TABLE music
    ADD CONSTRAINT FK_MUSIC_ON_RECORD_LABEL FOREIGN KEY (record_label_id) REFERENCES record_labels (id);

-- changeset dip4rip:1713271640981-15
ALTER TABLE playlist_music
    ADD CONSTRAINT FK_PLAYLIST_MUSIC_ON_INVENTORY_NUMBER FOREIGN KEY (inventory_number) REFERENCES music (inventory_number);

-- changeset dip4rip:1713271640981-16
ALTER TABLE playlist_music
    ADD CONSTRAINT FK_PLAYLIST_MUSIC_ON_PLAYLIST FOREIGN KEY (playlist_id) REFERENCES playlist (id);

-- changeset dip4rip:1713271640981-17
ALTER TABLE playlist
    ADD CONSTRAINT FK_PLAYLIST_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

